services:
  reportGeneratorDatabase:
    image: postgres:16
    restart: always
    env_file:
      - ./.env
    shm_size: 256mb
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
