services:
  reportClientDatabase:
    image: postgres:16
    restart: always
    env_file:
      - ./env/development.env
    shm_size: 256mb
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
